version: "3"
services:
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
    - 9090:9090
    networks:
      - my_network
    volumes:
    - prometheus:/etc/prometheus
volumes:
  prometheus:
    external: true

networks:
  my_network:
    driver: bridge
