version: "3"
services:
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    ports:
    - 9090:9090
    networks:
    - myNetwork
    volumes:
    - prometheus:/etc/prometheus

  grafana:
    build:  #позволяет собрать билд
      context: .
      dockerfile: ./Dockerfile
    restart: always #если контаинер упадет то он будет перезапущен ОТКАЗОУСТОЙЧИВОСТЬ
    container_name: grafana_my
    networks:
    - myNetwork
    ports:
    - 3000:3000

volumes:
  prometheus:
    external: true

networks:
  myNetwork:
    driver: bridge
